### ISSUE TITLE
(Old version) Cursor not visible on a triangle when picking color and using "FORE" (New version) Cursor doesn't exist anymore

### ISSUE THREAD

**Issue by thefireKS** [behreajj/AseTriPicker#1]
Hello! I really like your extension and would like to see it fully working. First of all, i found it a while ago, and noticed this issue today, that i wanted to try to fix by myself:
https://github.com/user-attachments/assets/66c95f85-95b9-421e-8176-8cb614cd3477
As you can see, the cursor is disappearing, when i interact with buttons

But in the new version there's simply no cursor that makes work with colors less predictable (i simply don't know where my previous color was located on a triangle)
If you're able to fix it and add cursor to the new version - i'd be really thankful

Cheers!

**Comment by behreajj** [comment]
I don’t have any plans on bringing back the reticle. If you prefer the old version, this commit might be a good place to return to: [7f7c757](https://github.com/behreajj/AseTriPicker/commit/7f7c7579834c13e229f2349bff6832df90f355d7).

**Comment by behreajj** [comment]
Please keep this open, as Github makes closed issues harder to find. Thank you.

Reference link(s) to what I think might be helpful for anyone interested: 
https://codeplea.com/triangular-interpolation
https://en.wikipedia.org/wiki/Barycentric_coordinate_system#Conversion_between_barycentric_and_Cartesian_coordinates .

**Comment by thefireKS** [comment]
Okay, no problem!

**Comment by behreajj** [comment]
Ok, I think I found something that will work. Please see if https://github.com/behreajj/AseTriPicker/commit/acc9db114664bac0a644b60471b835e4e4d2b406 (Friday, October 11, 2024) resolves this issue.

The reticle follows HSV prior to bit depth quantization so as to minimize jitteriness. If you select a color in the script dialog, then get that color from the color bar again, the shift should be expected. The lower the bit depth, the bigger the shift.

![cursorJump1](https://github.com/user-attachments/assets/d44c217e-d088-44f6-a333-d1fc296b28df)

![cursorJump2](https://github.com/user-attachments/assets/7b10a69d-7d8e-46ef-83ad-a60505a723bd)

**Comment by thefireKS** [comment]
That's awesome! Works perfectly, thank you very much, that covers all needs now :smile: 

I hope it wasn't hard to implement to you! Great job
